# Generated by Django 5.2.3 on 2025-07-18 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(max_length=10, unique=True)),
                ('segmento', models.CharField(max_length=50)),
                ('cotacao', models.FloatField()),
                ('ffo_yield', models.FloatField()),
                ('dividend_yield', models.FloatField()),
                ('pvp', models.FloatField()),
                ('valor_mercado', models.IntegerField()),
                ('liquidez', models.IntegerField()),
                ('qtd_imoveis', models.IntegerField()),
                ('cap_rate', models.FloatField()),
                ('vacancia_media', models.FloatField()),
                ('razao_social', models.CharField(max_length=100)),
                ('prazo_duracao', models.CharField(max_length=50)),
                ('tipo_gestao', models.CharField(max_length=50)),
                ('taxa_administracao', models.CharField(max_length=50)),
                ('vacancia', models.FloatField()),
                ('numero_cotistas', models.IntegerField()),
                ('cotas_emitidas', models.IntegerField()),
                ('valor_patrimonial_cota', models.FloatField()),
                ('valor_patrimonial', models.CharField(max_length=50)),
                ('ultimo_rendimento', models.FloatField()),
                ('dividend_yield_12_meses', models.FloatField()),
                ('yield_on_coast', models.FloatField()),
                ('pub_date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['papel'],
            },
        ),
        migrations.CreateModel(
            name='UserFavoriteFiis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiis.fiis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorito do Usuário',
                'verbose_name_plural': 'Favoritos dos Usuários',
                'unique_together': {('user', 'fiis')},
            },
        ),
    ]
