# Generated by Django 5.2.3 on 2025-07-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiis',
            name='cap_rate',
        ),
        migrations.RemoveField(
            model_name='fiis',
            name='cotacao',
        ),
        migrations.RemoveField(
            model_name='fiis',
            name='cotas_emitidas',
        ),
        migrations.RemoveField(
            model_name='fiis',
            name='dividend_yield',
        ),
        migrations.RemoveField(
            model_name='fiis',
            name='dividend_yield_12_meses',
        ),
        migrations.RemoveField(
            model_name='fiis',
            name='ffo_yield',
        ),
        migrations.RemoveField(
            model_name='fiis',
            name='liquidez',
        ),
        migrations.RemoveField(
            model_name='fiis',
            name='numero_cotistas',
        ),
        migrations.RemoveField(
            model_name='fiis',
            name='prazo_duracao',
        ),
        migrations.RemoveField(
            model_name='fiis',
            name='pub_date_time',
        ),
        migrations.RemoveField(
            model_name='fiis',
            name='pvp',
        ),
        migrations.RemoveField(
            model_name='fiis',
            name='qtd_imoveis',
        ),
        migrations.RemoveField(
            model_name='fiis',
            name='razao_social',
        ),
        migrations.RemoveField(
            model_name='fiis',
            name='segmento',
        ),
        migrations.RemoveField(
            model_name='fiis',
            name='taxa_administracao',
        ),
        migrations.RemoveField(
            model_name='fiis',
            name='tipo_gestao',
        ),
        migrations.RemoveField(
            model_name='fiis',
            name='ultimo_rendimento',
        ),
        migrations.RemoveField(
            model_name='fiis',
            name='vacancia',
        ),
        migrations.RemoveField(
            model_name='fiis',
            name='vacancia_media',
        ),
        migrations.RemoveField(
            model_name='fiis',
            name='valor_mercado',
        ),
        migrations.RemoveField(
            model_name='fiis',
            name='valor_patrimonial',
        ),
        migrations.RemoveField(
            model_name='fiis',
            name='valor_patrimonial_cota',
        ),
        migrations.RemoveField(
            model_name='fiis',
            name='yield_on_coast',
        ),
    ]
