# Generated by Django 5.2.3 on 2025-08-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiis', '0002_remove_fiis_cap_rate_remove_fiis_cotacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiis',
            options={'ordering': ['papel'], 'verbose_name': 'Fundo Imobiliário', 'verbose_name_plural': 'Fundos Imobiliários'},
        ),
        migrations.AddField(
            model_name='fiis',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='dividend_yield',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dividend Yield'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='dy_12m_acumulado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DY (12M) Acumulado'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='dy_12m_media',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DY (12M) Média'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='dy_3m_acumulado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DY (3M) Acumulado'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='dy_3m_media',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DY (3M) Média'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='dy_6m_acumulado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DY (6M) Acumulado'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='dy_6m_media',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DY (6M) Média'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='dy_ano',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DY Ano'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='dy_patrimonial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DY Patrimonial'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='liquidez_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Liquidez Diária (R$)'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='num_cotistas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Cotistas'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='p_vp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='P/VP'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='p_vpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='P/VPA'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='patrimonio_liquido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Patrimônio Líquido'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='preco_atual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Preço Atual (R$)'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='quant_ativos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quant. Ativos'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='rentabilidade_acumulada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rentab. Acumulada'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='rentabilidade_patr_acumulada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rentab. Patr. Acumulada'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='rentabilidade_patr_periodo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rentab. Patr. Período'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='rentabilidade_periodo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rentab. Período'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='setor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Setor'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='taxa_administracao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Taxa de Administração'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='taxa_gestao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Taxa de Gestão'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='taxa_performance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Taxa de Performance'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='ultimo_dividendo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Último Dividendo'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='variacao_patrimonial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Variação Patrimonial'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='variacao_preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Variação Preço'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='volatilidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Volatilidade'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='vpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='VPA'),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='papel',
            field=models.CharField(max_length=10, unique=True, verbose_name='Código do Fundo'),
        ),
    ]
