# Generated by Django 5.2.3 on 2025-08-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiis', '0004_alter_fiis_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiis',
            name='dy_3m_media',
        ),
        migrations.RemoveField(
            model_name='fiis',
            name='p_vp',
        ),
        migrations.RemoveField(
            model_name='fiis',
            name='p_vpa',
        ),
        migrations.RemoveField(
            model_name='fiis',
            name='rentabilidade_acumulada',
        ),
        migrations.RemoveField(
            model_name='fiis',
            name='rentabilidade_patr_acumulada',
        ),
        migrations.RemoveField(
            model_name='fiis',
            name='rentabilidade_patr_periodo',
        ),
        migrations.RemoveField(
            model_name='fiis',
            name='rentabilidade_periodo',
        ),
        migrations.RemoveField(
            model_name='fiis',
            name='taxa_gestao',
        ),
        migrations.RemoveField(
            model_name='fiis',
            name='taxa_performance',
        ),
        migrations.AddField(
            model_name='fiis',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fiis',
            name='cotacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Cotação'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='cotas_emitidas',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Cotas Emitidas'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='dy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DY'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='dy_pago_ult_12m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DY (3M) média'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='liquidez_unidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Liquidez por Unidade'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='mandato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fiis',
            name='prazo_duracao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prazo de Duração'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='publico_alvo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fiis',
            name='pvp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='P/VP'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='razao_social',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fiis',
            name='rentab_acumulada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rentab. Acumulada'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='rentab_patr_acumulada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rentab. Patr. Acumulada'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='rentab_patr_periodo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rentab. Patr. Período'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='rentab_periodo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rentab. Período'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='segmento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fiis',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Fundo'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='tipo_gestao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Gestão'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='ultimo_rendimento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Último Rendimento'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='vacancia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Vacância'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='valor_patrimonial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor Patrimonial'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='valor_patrimonial_unidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor Patrimonial por Unidade'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='variacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Variação'),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='dividend_yield',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dividend Yield'),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='dy_12m_acumulado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DY (12M) Acumulado'),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='dy_12m_media',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DY (12M) média'),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='dy_3m_acumulado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DY (3M) Acumulado'),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='dy_6m_acumulado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DY (6M) Acumulado'),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='dy_6m_media',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DY (6M) média'),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='dy_ano',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DY Ano'),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='dy_patrimonial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DY Patrimonial'),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='liquidez_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Liquidez Diária (R$)'),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='num_cotistas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº de Cotistas'),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='papel',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='patrimonio_liquido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Patrimônio Líquido'),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='preco_atual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Preço Atual (R$)'),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='quant_ativos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quant. Ativos'),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='taxa_administracao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Taxa de Administração'),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='ultimo_dividendo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Último Dividendo'),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='variacao_patrimonial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Variação Patrimonial'),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='variacao_preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Variação Preço'),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='volatilidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Volatilidade'),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='vpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='VPA'),
        ),
    ]
