# Generated by Django 5.2.3 on 2025-08-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiis', '0005_remove_fiis_dy_3m_media_remove_fiis_p_vp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiis',
            old_name='dy_pago_ult_12m',
            new_name='dy_3m_media',
        ),
        migrations.AddField(
            model_name='fiis',
            name='liquidez_diaria_rs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Liquidez Diária (R$)'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='p_vpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='P/VPA'),
        ),
        migrations.AddField(
            model_name='fiis',
            name='valor_patrimonial_cota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Variação Patrimonial'),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='liquidez_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Liquidez Diária'),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='mandato',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mandato'),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='papel',
            field=models.CharField(max_length=20, unique=True, verbose_name='Papel'),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='publico_alvo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Público-Alvo'),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='razao_social',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='segmento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Segmento'),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='setor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='valor_patrimonial_unidade',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Valor Patrimonial por Unidade'),
        ),
    ]
