# Generated by Django 5.2.3 on 2025-08-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiis', '0006_rename_dy_pago_ult_12m_fiis_dy_3m_media_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiis',
            name='taxa_administracao',
        ),
        migrations.AlterField(
            model_name='fiis',
            name='liquidez_unidade',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Liquidez por Unidade'),
        ),
    ]
