# Generated by Django 5.2.3 on 2025-08-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiis', '0007_remove_fiis_taxa_administracao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiisKpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(max_length=20, unique=True, verbose_name='Papel')),
                ('cotacao', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Cotação')),
                ('dy_12m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DY (12M)')),
                ('pvp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='PVP')),
                ('liquidez_diaria', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Liquidez Diária')),
                ('liquidez_diaria_unidade', models.CharField(blank=True, max_length=20, null=True, verbose_name='Liquidez por Unidade')),
                ('variacao_12m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Variação 12M')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KPI do FII',
                'verbose_name_plural': 'KPIs dos FII',
                'ordering': ['papel'],
            },
        ),
    ]
