# Generated by Django 5.2.3 on 2025-09-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiis', '0008_fiiskpi'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiisInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(max_length=20, unique=True, verbose_name='Papel')),
                ('razao_social', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razão Social')),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ')),
                ('publico_alvo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Público-Alvo')),
                ('mandato', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mandato')),
                ('segmento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segmento')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Fundo')),
                ('prazo_duracao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prazo de Duração')),
                ('tipo_gestao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Gestão')),
                ('vacancia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Vacância')),
                ('cotas_emitidas', models.BigIntegerField(blank=True, null=True, verbose_name='Cotas Emitidas')),
                ('valor_patrimonial_cota', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Variação Patrimonial')),
                ('valor_patrimonial', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor Patrimonial')),
                ('ultimo_rendimento', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Último Rendimento')),
                ('valor_patrimonial_unidade', models.CharField(blank=True, max_length=20, null=True, verbose_name='Valor Patrimonial por Unidade')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Informações do FII',
                'verbose_name_plural': 'Informações dos FII',
                'ordering': ['papel'],
            },
        ),
    ]
