# Generated by Django 5.2.3 on 2025-09-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiis', '0009_fiisinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiisinfo',
            old_name='tipo',
            new_name='tipo_fundo',
        ),
        migrations.AddField(
            model_name='fiisinfo',
            name='numero_cotistas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº de Cotistas'),
        ),
        migrations.AddField(
            model_name='fiisinfo',
            name='taxa_administracao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Taxa de Administração'),
        ),
    ]
