# Generated by Django 5.2.3 on 2025-09-03 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiis', '0010_rename_tipo_fiisinfo_tipo_fundo_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fiis',
            table='fiis',
        ),
        migrations.AlterModelTable(
            name='fiisinfo',
            table='fiis_info',
        ),
        migrations.AlterModelTable(
            name='fiiskpi',
            table='fiis_kpi',
        ),
        migrations.AlterModelTable(
            name='userfavoritefiis',
            table='user_favorite_fiis',
        ),
    ]
