# Generated by Django 5.2.3 on 2025-09-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiis', '0011_alter_fiis_table_alter_fiisinfo_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiisFundsExplorer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(max_length=20, unique=True, verbose_name='Papel')),
                ('setor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Setor')),
                ('cotacao', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Preço Atual')),
                ('liquidez_diaria_rs', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Liquidez Diária (R$)')),
                ('ultimo_dividendo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Último Dividendo')),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Dividend Yield')),
                ('dy_3m_acumulado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='DY (3M) Acumulado')),
                ('dy_6m_acumulado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='DY (6M) Acumulado')),
                ('dy_12m_acumulado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='DY (12M) Acumulado')),
                ('dy_3m_media', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='DY (3M) Média')),
                ('dy_6m_media', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='DY (6M) Média')),
                ('dy_12m_media', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='DY (12M) Média')),
                ('dy_ano', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='DY (Ano)')),
                ('variacao_preco', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Variação Preço')),
                ('rentab_periodo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Rentabilidade do Período')),
                ('rentab_acumulada', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Rentabilidade Acumulada')),
                ('patrimonio_liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Patrimônio Líquido')),
                ('vpa', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='VPA')),
                ('p_vpa', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='P/VPA')),
                ('dy_patrimonial', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='DY Patrimonial')),
                ('variacao_patrimonial', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Variação Patrimonial')),
                ('rentab_patr_periodo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Rentabilidade Patrimonial do Período')),
                ('rentab_patr_acumulada', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Rentabilidade Patrimonial Acumulada')),
                ('quant_ativos', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de Ativos')),
                ('volatilidade', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Volatilidade')),
                ('num_cotistas', models.IntegerField(blank=True, null=True, verbose_name='Nº de Cotistas')),
            ],
            options={
                'verbose_name': 'Fundo Imobiliário',
                'verbose_name_plural': 'Fundos Imobiliários',
                'db_table': 'fiis_funds_explorer',
                'ordering': ['papel'],
            },
        ),
    ]
