# Generated by Django 5.2.3 on 2025-09-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiis', '0012_fiisfundsexplorer'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiisfundsexplorer',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
