# Generated by Django 5.2.3 on 2025-07-24 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'ordering': ['papel'],
            },
        ),
        migrations.CreateModel(
            name='UserFavoriteAcoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acoes.acoes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorito do Usuário',
                'verbose_name_plural': 'Favoritos dos Usuários',
                'unique_together': {('user', 'acoes')},
            },
        ),
    ]
