# Generated by Django 5.2.3 on 2025-08-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acoes',
            name='ativo_circulante',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='ativos',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='cagr_lucros_5_anos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='cagr_receitas_5_anos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='carteira_investidor_10',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='cotation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='disponibilidade',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='divida_bruta',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='divida_bruta_patrimonio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='divida_liquida',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='divida_liquida_ebit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='divida_liquida_ebitda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='divida_liquida_patrimonio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='dividend_yield',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='dy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='ev_ebit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='ev_ebitda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='free_float',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='giro_ativos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='liquidez_corrente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='liquidez_media_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='lpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='margem_bruta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='margem_ebit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='margem_ebitda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='margem_liquida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='numero_papeis',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='p_ativo_circ_liq',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='p_cap_giro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='passivos_ativos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='pativo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='patrimonio_ativos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='patrimonio_liquido',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='payout',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='pebit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='pebitda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='pl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='psr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='pv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='roa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='roe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='roic',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='segmento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='segmento_listagem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='setor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='tag_along',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='ticker_img',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='valor_firma',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='valor_mercado',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='variation_12m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='vpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
