# Generated by Django 5.2.3 on 2025-08-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0002_acoes_ativo_circulante_acoes_ativos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acoes',
            name='free_float',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
