# Generated by Django 5.2.3 on 2025-08-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0003_alter_acoes_free_float'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acoes',
            name='free_float',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
