# Generated by Django 5.2.3 on 2025-08-05 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0004_alter_acoes_free_float'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acoes',
            name='carteira_investidor_10',
        ),
        migrations.RemoveField(
            model_name='acoes',
            name='dividend_yield',
        ),
    ]
