# Generated by Django 5.2.3 on 2025-08-05 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0005_remove_acoes_carteira_investidor_10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acoes',
            name='liquidez_media_diaria',
        ),
    ]
