# Generated by Django 5.2.3 on 2025-08-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0006_remove_acoes_liquidez_media_diaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acoes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
