# Generated by Django 5.2.3 on 2025-08-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0007_alter_acoes_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='acoes',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acoes',
            name='rank_ponderado',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
