# Generated by Django 5.2.3 on 2025-08-14 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0008_acoes_rank_acoes_rank_ponderado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acoes',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='acoes',
            name='rank_ponderado',
        ),
    ]
