# Generated by Django 5.2.3 on 2025-08-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0009_remove_acoes_rank_remove_acoes_rank_ponderado'),
    ]

    operations = [
        migrations.AddField(
            model_name='acoes',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
