# Generated by Django 5.2.3 on 2025-09-02 23:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0010_acoes_data_atualizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acoes',
            name='data_atualizacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
